#!/bin/bash
# Regenerate index.yaml from pipelines/*.yaml. The format the operator
# fetches is `{pipelines: [...]}` where each entry has the same fields
# as a per-pipeline file (minus the `sample` field, which is for human
# review only).
set -e
cd "$(dirname "$0")/.."

python3 - <<'PY'
from pathlib import Path
import json

ROOT = Path(".")
PIPELINES = ROOT / "pipelines"
INDEX = ROOT / "index.yaml"

import yaml

entries = []
for f in sorted(PIPELINES.glob("*.yaml")):
    d = yaml.safe_load(f.read_text())
    if d is None:
        continue
    # Strip the human-review-only fields.
    d.pop("sample", None)
    entries.append(d)

# Emit by hand so VRL stays as a literal block scalar (PyYAML's safe_dump
# wraps long strings, which would change semantics).
def yamlify(s):
    return json.dumps(s)

parts = [
    "# Auto-generated by scripts/build-index.sh from pipelines/*.yaml.",
    "# Edit pipelines/<src>.yaml and re-run the script.",
    "pipelines:",
]
for e in entries:
    parts.append(f"  - sourceId: {yamlify(e['sourceId'])}")
    parts.append(f"    fingerprint: {yamlify(e.get('fingerprint',''))}")
    parts.append(f"    family: {yamlify(e.get('family',''))}")
    parts.append(f"    ocsfClass: {int(e['ocsfClass'])}")
    parts.append(f"    description: {yamlify(e.get('description',''))}")
    vrl = e['vrl']
    if not vrl.endswith('\n'):
        vrl = vrl + '\n'
    indented = '\n'.join('      ' + l if l else '' for l in vrl.split('\n'))
    parts.append(f"    vrl: |\n{indented}".rstrip())

INDEX.write_text('\n'.join(parts) + '\n')
print(f"wrote index.yaml with {len(entries)} entries")
PY
